### ISSUE TITLE
Διδακτορικό στην Πληροφορική

### ISSUE THREAD

**Issue by vvdimako** [vvdimako/cseuoi-thesis#10]
Ο νέος κανονισμός διδακτορικών σπουδών αναφέρει ότι απονέμουμε Δ.Δ. και όχι Δ.Δ. στην Πληροφορική, οπότε το "στην Πληροφορική" πρέπει να το βγάλουμε από το title page...

**Comment by akestoridis** [comment]
Αφαίρεσα τη φράση "στην Πληροφορική/in Computer Science" από τα title pages και τα abstract pages στην περίπτωση της Διδακτορικής Διατριβής.
Σχετικά με το αγγλικό title page, θέλετε να μεταφράσουμε το "Διδακτορικό Δίπλωμα" ως "Doctor of Philosophy degree" ή κάπως αλλιώς;

**Comment by vvdimako** [comment]
Ναι,
... for the degree of 
Doctor of Philosophy
