### ISSUE TITLE
Problem writing proofs under the "en" option

### ISSUE THREAD

**Issue by npapanik** [vvdimako/cseuoi-thesis#16]
The greek term "Απόδειξη" appears instead of "Proof" when trying to write a proof despite the fact that the "en" option is enabled. More specifically, I'm using "\documentclass[en,phd]{cseuoi-thesis}". A quick fix is to add the line "\renewcommand{\proofname}{Proof}" inside the cls file when "en" option is declared (I used line 219).

**Comment by akestoridis** [comment]
Fixed with commit f37c69b7135c46cc46337cbf54fa7b5fd16635a0.
