### ISSUE TITLE
Remove unused packages

### ISSUE THREAD

**Issue by psxlover** [vvdimako/cseuoi-thesis#2]
There are a lot of packages included that are never used (caption is also deprecated). We should probably remove them and let the user add only what he needs.

**Comment by akestoridis** [comment]
We should also move the packages that are definitely necessary in the .cls file.

**Comment by akestoridis** [comment]
I do not think that the user should be able to change the font size or the typeface.
In this case, we should move the corresponding commands in the .cls file.
