### ISSUE TITLE
"ΕΙΔΙΚΕΥΣΗΣ"

### ISSUE THREAD

**Issue by psxlover** [vvdimako/cseuoi-thesis#3]
Γιατί είπαμε ότι μπήκε το ειδίκευσης στον τίτλο? Το "μεταπτυχιακού/διδακτορικού διπλώματος ειδίκευσης στην πληροφορική με εξειδίκευση στο..." δε μου ακούγεται καλά, το ειδίκευση στην ίδια πρόταση με το εξειδίκευση κάπως μου κάνει. Όχι πως με νοιάζει και τόσο, γενικός και τα περί εξεταστικής επιτροπής άχρηστα μου φαίνονται.

Το ίδιο και με το αγγλικό, "master of science in computer science" μου φαίνεται πλεονασμός, και λογικά θα είναι καλύτερα να χρησιμοποιήσουμε την συντομογραφία ΜSc. Αλλιώς θα πρέπει και τη διπλωματική στα αγγλικά να την έχουμε "Philosophiae Doctor" ή ακόμα χειρότερα "Doctor of Philosophy" αντί για PhD.

**Comment by akestoridis** [comment]
Ο όρος "Ειδίκευσης" είναι μόνο για το M.Sc., όπως μπορείς να δεις στα παρακάτω δύο αποσπάσματα από τον [οδηγό σπουδών](http://www.cs.uoi.gr/upFiles/uploand_doc/O.S.%20Plhroforikhs%202015-16%20internet%20%281%29.pdf):

> Το Τμήμα επίσης διαθέτει από το 1998 οργανωμένο Πρόγραμμα Μεταπτυχιακών Σπουδών (Π.Μ.Σ.) και απονέμει Μεταπτυχιακό Δίπλωμα Ειδίκευσης (Μ.Δ.Ε.) καθώς και Διδακτορικό Δίπλωμα. 
> 
> Το Τμήμα Μηχανικών Η/Υ και Πληροφορικής του Πανεπιστημίου Ιωαννίνων οργανώνει και λειτουργεί από το Ακαδημαϊκό Έτος 1998-1999, Πρόγραμμα Μεταπτυχιακών Σπουδών (Π.Μ.Σ.) με τίτλο «Πληροφορική» και απονέμει Μεταπτυχιακό Δίπλωμα Ειδίκευσης (Μ.Δ.Ε.) στις εξής εξειδικεύσεις στην Πληροφορική:
> - Υπολογιστικά Συστήματα
> - Θεωρία Επιστήμης Υπολογιστών
> - Λογισμικό
> - Επιστημονικοί Υπολογισμοί
> - Τεχνολογίες - Εφαρμογές

Επομένως, στο title page θα πρέπει να έχουμε "για την απόκτηση του Μεταπτυχιακού Διπλώματος Ειδίκευσης" για Master's Thesis, ενώ για Ph.D. Thesis θα πρέπει να έχουμε "για την απόκτηση Διδακτορικού Διπλώματος".

Σχετικά με τους αγγλικούς όρους, προφανώς στη σελίδα με τις περιλήψεις θα πρέπει να χρησιμοποιήσουμε τις συντομογραφίες M.Sc./Μ.Δ.Ε ή Ph.D./Δ.Δ., αλλά δυστυχώς στο title page νομίζω πως πρέπει να έχουμε τους όρους χωρίς συντομογραφίες.

**Comment by vvdimako** [comment]
Ναι, ο Δημήτρης έχει δίκιο.
