### ISSUE TITLE
File layout

### ISSUE THREAD

**Issue by psxlover** [vvdimako/cseuoi-thesis#6]
I don't like the front/main/backmatter layout.
I believe there should be just two folders with the .tex files, one containing all the "Chapter" files (and perhaps the bibliography) and another containing all of the rest, since the user only edit's them once.

**Comment by vvdimako** [comment]
It is OK, gives the author a sense of what goes where; there is no real need to save just 1 folder.
I don't like the "mainmatter" name; I prefer plain "content". So, please, let's change to the following structure (for various reasons, i would prefer to keep lowercase names of the folders):
frontmatter/
backmatter/
content/
figures/
and if need arises, we will add one more folder "styles/" or "include/".
