### ISSUE TITLE
A Master's Thesis

### ISSUE THREAD

**Issue by psxlover** [vvdimako/cseuoi-thesis#8]
Το "A Master's Thesis" στον τίτλο ακούγεται λάθος. Δεν είναι γενικά και αόριστα "ενός" μεταπτυχιακού η διπλωματική. Ακούγεται σαν να μιλάει κάποιος για τον εαυτό του στο τρίτο πρόσωπο.

**Comment by akestoridis** [comment]
Χωρίς το άρθρο "a" δεν βγάζει νόημα σαν πρόταση "Master's Thesis submitted to...".
Με την ίδια λογική ούτε στα ελληνικά θα έπρεπε να είχαμε το άρθρο "η", αλλά χωρίς αυτό δεν βγάζει νόημα η αντίστοιχη πρόταση "Η Διδακτορική Διατριβή υποβάλλεται στην...".

Προφανώς το ένα δεν είναι ακριβής μετάφραση του άλλου, όπως και άλλα σημεία του title page, ωστόσο είναι ότι πιο λογικό μπορούσα να σκεφτώ.
Γενικότερα, κοίταξα διατριβές από άλλα πανεπιστήμια και παρατήρησα ότι συνηθίζεται η έκφραση "A Master's Thesis submitted to..." καθώς και το πιο γενικό "A Thesis submitted to...".

**Comment by psxlover** [comment]
> Χωρίς το άρθρο "a" δεν βγάζει νόημα σαν πρόταση "Master's Thesis submitted to...".

Δεν εννοούσα να μπει χωρίς το "Α" μόνο, το "Master Thesis" χωρίς 's προσδιορίζει τι είναι το κείμενο που ακολουθεί, και το κείμενο από κάτω αποτελεί άλλη πρόταση, σκέψου το σαν να υπάρχει τελεία μετά το master thesis.

**Comment by akestoridis** [comment]
Στην ελληνική σελίδα τίτλου, υποτίθεται ότι υπάρχει τελεία μετά τον τίτλο της διατριβής και μετά ξεκινάει η πρόταση "Η Διδακτορική Διατριβή υποβάλλεται στην...".
Επομένως, νομίζω ότι θα πρέπει και η αγγλική σελίδα τίτλου να ακολουθεί την ίδια λογική.
Ωστόσο, ακόμα και αν υποθέσουμε ότι η πρόταση ξεκινάει μετά τη λέξη Thesis/Dissertation, δεν βγάζει νόημα να ξεκινάει μία πρόταση με "Submitted to...".

Σχετικά με το θέμα του προδιορισμού του κειμένου, πιστεύω ότι θα πρέπει να καταλήξουμε ποια ονομασία είναι σωστή, "Master's Thesis" ή "Master Thesis".
Από ότι έχω διαβάσει και οι δύο ονομασίες χρησιμοποιούνται, αλλά στα περισσότερα επίσημα έγγραφα χρησιμοποιείται η ονομασία "Master's Thesis".
Ακόμα και το BibTeX χρησιμοποιεί αυτή την ονομασία για [mastersthesis](https://en.wikipedia.org/wiki/BibTeX#Entry_types) αναφορές.
Γνωρίζω ωστόσο ότι στην [ιστοσελίδα της σχολής](http://cse.uoi.gr/index.php?menu=techReports&searchID=all) αναφερόμαστε στις μεταπτυχιακές εργασίες εξειδίκευσης ως "Master Thesis".
Γενικά, το βασικότερο πιστεύω ότι είναι να καταλήξουμε σε μία από τις δύο ονομασίες και να χρησιμοποιούμε παντού την ίδια.
